// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://etsxvctwsilgqzpqpmzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV0c3h2Y3R3c2lsZ3F6cHFwbXp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4ODkzNjAsImV4cCI6MjA2MjQ2NTM2MH0.r82HUrtQu-y8Mqtwpx6i2CUaoawjNWVbUslAMRK5jbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);